risky: true
version: 8.0
preset: none
enabled:
  - align_double_arrow
  - align_phpdoc
  - allman_braces
  - alpha_ordered_imports
  - alpha_ordered_traits
  - array_indentation
  - array_push
  - assign_null_coalescing_to_coalesce_equal
  - backtick_to_shell_exec
  - binary_operator_spaces
  - blank_line_after_namespace
  - blank_line_after_opening_tag
  - blank_line_before_break
  - blank_line_before_cases
  - blank_line_before_continue
  - blank_line_before_declare
  - blank_line_before_do
  - blank_line_before_exit
  - blank_line_before_for
  - blank_line_before_goto
  - blank_line_before_if
  - blank_line_before_include
  - blank_line_before_return
  - blank_line_before_switch
  - blank_line_before_throw
  - blank_line_before_try
  - blank_line_before_while
  - blank_line_before_yield

finder:
  exclude:
    - "modules"
    - "node_modules"
    - "nova"
    - "nova-components"
    - "storage"
    - "spark"
    - "vendor"
  name: "*.php"
  not-name:
    - "*.blade.php"
    - "_ide_helper.php"
