risky: true
version: 8.0
preset: none
enabled:
  - align_double_arrow
  - align_phpdoc
  - allman_braces
  - alpha_ordered_imports
  - alpha_ordered_traits
  - array_indentation
  - array_push
  - assign_null_coalescing_to_coalesce_equal
  - backtick_to_shell_exec
  - binary_operator_spaces
  - blank_line_after_namespace
  - blank_line_after_opening_tag
  - blank_line_before_break
  - blank_line_before_cases
  - blank_line_before_continue
  - blank_line_before_declare
  - blank_line_before_do
  - blank_line_before_exit
  - blank_line_before_for
  - blank_line_before_goto
  - blank_line_before_if
  - blank_line_before_include
  - blank_line_before_return
  - blank_line_before_switch
  - blank_line_before_throw
  - blank_line_before_try
  - blank_line_before_while
  - blank_line_before_yield
  - cast_spaces
  - class_keyword_remove
  - class_reference_name_casing
  - clean_namespace
  - combine_consecutive_issets
  - combine_consecutive_unsets
  - combine_nested_dirname
  - comment_to_phpdoc
  - compact_nullable_typehint
  - concat_with_spaces
  - const_separation
  - const_visibility_required
  - declare_equal_normalize
  - declare_strict_types
  - deprecation_error_suppression
  - die_to_exit
  - dir_constant
  - doctrine_annotation_array_assignment
  - doctrine_annotation_braces
  - doctrine_annotation_indentation
  - doctrine_annotation_spaces
  - elseif
  - empty_loop_body_braces
  - empty_loop_condition
  - encoding
  - ereg_to_preg
  - escape_implicit_backslashes
  - explicit_indirect_variable
  - explicit_string_variable
  - final_internal_class
  - final_public_method_for_abstract_class
  - fopen_flag_order
  - fopen_flags
  - full_opening_tag
  - fully_qualified_strict_types
  - function_declaration
  - function_to_constant
  - function_typehint_space
  - get_class_to_class_keyword
  - group_import
  - hash_to_slash_comment
  - heredoc_indentation
  - heredoc_to_nowdoc
  - implode_call
  - include
  - indentation
  - integer_literal_case
  - is_null
  - laravel_phpdoc_alignment
  - laravel_phpdoc_order
  - laravel_phpdoc_separation
  - linebreak_after_opening_tag
  - logical_operators
  - lowercase_cast
  - lowercase_constants
  - lowercase_keywords
  - lowercase_static_reference
  - magic_constant_casing
  - magic_method_casing
  - mb_str_functions
  - method_argument_space_strict
  - method_chaining_indentation
  - method_separation
  - method_visibility_required
  - modernize_strpos
  - modernize_types_casting
  - multiline_comment_opening_closing
  - native_constant_invocation_strict
  - native_function_casing
  - native_function_invocation_symfony
  - native_function_type_declaration_casing
  - new_with_braces
  - no_alias_functions
  - no_alternative_syntax
  - no_binary_string
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_return
  - no_blank_lines_after_throw
  - no_blank_lines_around_break
  - no_blank_lines_around_cases
  - no_blank_lines_around_continue
  - no_blank_lines_around_switch
  - no_blank_lines_between_imports
  - no_break_comment
  - no_closing_tag
  - no_empty_comment
  - no_empty_phpdoc
  - no_empty_statement
  - no_extra_block_blank_lines
  - no_extra_consecutive_blank_lines
  - no_homoglyph_names
  - no_leading_import_slash
  - no_leading_namespace_whitespace
  - no_multiline_whitespace_around_double_arrow
  - no_multiline_whitespace_before_semicolons
  - no_php4_constructor
  - no_short_bool_cast
  - no_short_echo_tag
  - no_singleline_whitespace_before_semicolons
  - no_space_around_double_colon
  - no_spaces_after_function_name
  - no_spaces_inside_offset
  - no_spaces_inside_parenthesis
  - no_spaces_outside_offset
  - no_superfluous_elseif
  - no_superfluous_phpdoc_tags_symfony
  - no_trailing_comma_in_list_call
  - no_trailing_comma_in_singleline_array
  - no_trailing_comma_in_singleline_function_call
  - no_trailing_whitespace
  - no_trailing_whitespace_in_comment
  - no_trailing_whitespace_in_string
  - no_unneeded_control_parentheses
  - no_unneeded_curly_braces
  - no_unneeded_final_method
  - no_unneeded_import_alias
  - no_unreachable_default_argument_value
  - no_unset_cast
  - no_unused_imports
  - no_unused_lambda_imports
  - no_useless_else
  - no_useless_return
  - no_useless_sprintf
  - no_whitespace_before_comma_in_array

finder:
  exclude:
    - "modules"
    - "node_modules"
    - "nova"
    - "nova-components"
    - "storage"
    - "spark"
    - "vendor"
  name: "*.php"
  not-name:
    - "*.blade.php"
    - "_ide_helper.php"
