version: "3.9"

services:
  tests:
    image: composer:2.1
    volumes:
      - ./:/app
    working_dir: /app
    command: >
      sh -c "rm -f ./composer.lock &&
             composer validate &&
             composer install &&
             php ./vendor/bin/phpstan analyze --ansi --debug --memory-limit 512M &&
             php ./vendor/bin/phpunit --coverage-text &&
             php ./vendor/bin/phpcs"

  format:
    image: composer:2.1
    volumes:
      - ./:/app
    working_dir: /app
    command: >
      sh -c "rm -f ./composer.lock &&
              composer install &&
              php ./vendor/bin/phpcbf"
