name: Report a Bug
description: Encountering unexpected problems or unintended behavior? Let us know!

body:
  - type: markdown
    attributes:
      value: |
        **Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/responsible-disclosure-policy) details the procedure for disclosing security issues.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: This can be reproduced using [the quickstart sample application](https://github.com/auth0-samples/laravel).
          required: true
        - label: I have looked at [the README](https://github.com/auth0/laravel-auth0/#readme) and have not found a solution.
          required: true
        - label: I have looked at [the `docs` directory](https://github.com/auth0/laravel-auth0/blob/main/docs) and have not found a solution.
          required: true
        - label: I have searched [previous issues](https://github.com/auth0/laravel-auth0/issues) and have not found a solution.
          required: true
        - label: I have searched [the Auth0 Community](https://community.auth0.com/tag/laravel) and have not found a solution.
          required: true
        - label: I agree to uphold [the Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
          required: true

  - type: dropdown
    id: laravel
    attributes:
      label: Laravel Version
      description: What version of Laravel are you using? (`composer show | grep laravel/framework`)
      options:
        - 10
        - 9
        - Other (specify below)
    validations:
      required: true

  - type: dropdown
    id: sdk
    attributes:
      label: SDK Version
      description: What version of our SDK are you using? (`composer show | grep auth0/login`)
      options:
        - 7.13
        - 7.12
        - 7.11
        - 7.10
        - 7.9
        - 7.8
        - 7.7
        - 7.6
        - 7.5
        - 7.4
        - 7.3
        - 7.2
        - 7.1
        - 7.0
        - Other (specify below)
    validations:
      required: true

  - type: dropdown
    id: php
    attributes:
      label: PHP Version
      description: What version of PHP are you running? (`php -v`)
      options:
        - PHP 8.3
        - PHP 8.2
        - Other (specify below)
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: Provide a description of the issue, including what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: bug-reproduction
    attributes:
      label: How can we reproduce this issue?
      description: Detail the steps taken to reproduce this error. If possible, please provide a GitHub repository to demonstrate the issue.
    validations:
      required: true
