name: Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  composer-normalize:
    name: Composer Normalize
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Composer normalize
        uses: docker://ergebnis/composer-normalize-action

  fossa-scan:
    name: FOSSA License Compliance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: "Run FOSSA Scan"
        uses: fossas/fossa-action@main
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}

      - name: "Run FOSSA Test"
        uses: fossas/fossa-action@main
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
          run-tests: true
