name: "Composer Validate"

on:
  pull_request_target: {}
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: composer validate
