name: "PEST"

on:
  pull_request: {}
  push:
    branches:
      - main

permissions: {}

jobs:
  pest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          coverage: pcov

      - run: composer install --no-progress

      - run: vendor/bin/pest --order-by random --fail-on-risky --stop-on-defect --coverage --parallel --min=95

      - uses: codecov/codecov-action@v3
        with:
          directory: ./coverage/
          flags: unittests
