name: "Composer Normalize"

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

permissions: {}

jobs:
  normalize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: docker://ergebnis/composer-normalize-action
