name: "Composer Normalize"

on:
  pull_request_target: {}
  push:
    branches:
      - main

jobs:
  normalize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker://ergebnis/composer-normalize-action
