name: SCA

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  snyk-cli:
    uses: auth0/devsecops-tooling/.github/workflows/sca-scan.yml@main
    with:
      php-version: "8.2"
      pre-scan-commands: |
        composer install --no-interaction --prefer-dist
    secrets: inherit
