name: Static analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1"]

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Execute PHPStan
        run: vendor/bin/phpstan analyze --no-progress -c .github/workflows-configs/phpstan.neon.dist

  phpinsights:
    name: PHPInsights
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1"]

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Execute PHPInsights
        run: vendor/bin/phpinsights --no-interaction -c .github/workflows-configs/phpinsights.php

  rector:
    name: Rector
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1"]

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Execute Rector
        run: vendor/bin/rector process src --dry-run -c .github/workflows-configs/rector.php

  pest:
    name: Pest
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1"]

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          extensions: mbstring

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Execute Pest
        run: vendor/bin/pest --ci --coverage -c .github/workflows-configs/phpunit.xml.dist
